/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "GOOGLE_CLIENT_ID": {
      "type": "neo.neo.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "neo.neo.Secret"
      "value": string
    }
    "MyAuth": {
      "type": "neo.aws.Auth"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "neo.aws.Bucket"
    }
    "MyNextjsSite": {
      "type": "neo.aws.Nextjs"
      "url": string
    }
    "MyRouter": {
      "type": "neo.aws.Router"
      "url": string
    }
    "MyRouterApp": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyRouterAstro": {
      "type": "neo.aws.Astro"
      "url": string
    }
    "MyStaticSite": {
      "type": "neo.aws.StaticSite"
      "url": string
    }
    "MyVpc": {
      "type": "neo.aws.Vpc"
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}