/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyQueue": {
      "type": "neo.aws.Queue"
      "url": string
    }
    "MyQueuePurger": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyQueueSeeder": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyService": {
      "service": string
      "type": "neo.aws.Service"
      "url": string
    }
    "MyVpc": {
      "type": "neo.aws.Vpc"
    }
  }
}
