/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyApp": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyConfig": {
      "database": string
      "host": string
      "namespace": string
      "password": string
      "port": number
      "type": "neo.neo.Linkable"
      "username": string
    }
    "MyService": {
      "service": string
      "type": "neo.aws.Service"
    }
    "MyVpc": {
      "type": "neo.aws.Vpc"
    }
  }
}
