/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "FastAPI": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyLinkableValue": {
      "foo": string
      "type": "neo.neo.Linkable"
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}