/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "MyBucket": {
      "name": string
      "type": "neo.aws.Bucket"
    }
    "MyWeb": {
      "type": "neo.aws.TanstackStart"
      "url": string
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}