/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {

}
interface ImportMeta {
  readonly env: ImportMetaEnv
}