/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyFunction": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyService": {
      "service": string
      "type": "neo.aws.Service"
      "url": string
    }
    "MyVpc": {
      "type": "neo.aws.Vpc"
    }
  }
}
