/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyApi": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyEmail": {
      "sender": string
      "type": "neo.aws.Email"
    }
  }
}
