/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "Hono": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "neo.aws.Bucket"
    }
    "Router": {
      "type": "neo.aws.Router"
      "url": string
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}