/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyRealtime": {
      "authorizer": string
      "endpoint": string
      "type": "neo.aws.Realtime"
    }
    "MyWeb": {
      "type": "neo.aws.Nextjs"
      "url": string
    }
  }
}
