/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "MyApi": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyAuth": {
      "type": "neo.aws.Auth"
      "url": string
    }
    "MyWeb": {
      "type": "neo.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}