/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
import "neo"
declare module "neo" {
  export interface Resource {
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "neo" {
  export interface Resource {
    "MyStorage": cloudflare.KVNamespace
    "Worker": cloudflare.Service
  }
}
