/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "ExtBucket": {
      "type": "neo.cloudflare.Bucket"
    }
    "MyBucket": {
      "type": "neo.cloudflare.Bucket"
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}