/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "neo"
declare module "neo" {
  export interface Resource {
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "neo" {
  export interface Resource {
    "Hono": cloudflare.Service
    "MyBucket": cloudflare.R2Bucket
  }
}

import "neo"
export {}