/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MySite": {
      "type": "neo.aws.StaticSite"
      "url": string
    }
  }
}
