/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyApp": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "MyRedis": {
      "clusterArn": string
      "host": string
      "password": string
      "port": number
      "type": "neo.aws.Redis"
      "username": string
    }
    "MyVpc": {
      "type": "neo.aws.Vpc"
    }
  }
}
