/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "neo"
export {}
declare module "neo" {
  export interface Resource {
    "MyWeb": {
      "type": "neo.aws.Nextjs"
      "url": string
    }
  }
}
