/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "MyWeb": {
      "type": "neo.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}