/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "Bus": {
      "arn": string
      "name": string
      "type": "neo.aws.Bus"
    }
    "Publisher": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}