/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "neo" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "Astro": {
      "type": "neo.aws.Astro"
      "url": string
    }
    "Database": {
      "name": string
      "type": "neo.aws.Dynamo"
    }
    "MyBucket": {
      "name": string
      "type": "neo.aws.Bucket"
    }
    "StaticSite": {
      "type": "neo.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="neo-env.d.ts" />

import "neo"
export {}