/* This file is auto-generated by NEO. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "neo"
export {}
import "neo"
declare module "neo" {
  export interface Resource {
    "Cloudflared": {
      "service": string
      "type": "neo.aws.Service"
    }
    "Lambda": {
      "name": string
      "type": "neo.aws.Function"
      "url": string
    }
    "Postgres": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "neo.aws.Postgres"
      "username": string
    }
    "Vpc": {
      "type": "neo.aws.Vpc"
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "neo" {
  export interface Resource {
    "Worker": cloudflare.Service
  }
}
