[project]
name = "functions"
version = "0.1.0"
description = "Lambda function (container-mode)handlers"
dependencies = ["core", "neo"]
requires-python = "==3.11.*"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
core = { workspace = true }
neo = { git = "https://github.com/neopilot-ai/neo.git", branch = "dev", subdirectory = "sdk/python" }
